export const FETCH_USER = "FETCH_USER";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_FLASH_CARDS = "FETCH_FLASH_CARDS";
export const CLEAR_FLASH_CARDS = "CLEAR_FLASH_CARDS";
