export const FETCH_USER = "FETCH_USER";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const NEW_CATEGORY = "NEW_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SET_CATEGORIES_DELETE = "SET_CATEGORIES_DELETE";
export const SET_JUST_DELETED = "SET_JUST_DELETED";

export const FETCH_FLASH_CARDS = "FETCH_FLASH_CARDS";
export const CLEAR_FLASH_CARDS = "CLEAR_FLASH_CARDS";

export const SET_MODAL_INFO = "SET_MODAL_INFO";

export const SET_MODAL_NEW_CAT_SHOW = "SET_MODAL_NEW_CAT_SHOW";
export const SET_MODAL_EDIT_CAT_SHOW = "SET_MODAL_EDIT_CAT_SHOW";
export const SET_MODAL_DELETE_SHOW = "SET_MODAL_DELETE_SHOW";

export const SET_MODAL_NEW_FLASH_SHOW = "SET_MODAL_NEW_FLASH_SHOW";
export const SET_MODAL_EDIT_FLASH_SHOW = "SET_MODAL_EDIT_FLASH_SHOW";

export const SET_TOAST_INFO = "SET_TOAST_INFO";
export const SET_TOAST_SHOW = "SET_TOAST_SHOW";
