export const FETCH_USER = "FETCH_USER";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SET_CATEGORIES_DELETE = "SET_CATEGORIES_DELETE";

export const FETCH_FLASH_CARDS = "FETCH_FLASH_CARDS";
export const CLEAR_FLASH_CARDS = "CLEAR_FLASH_CARDS";

export const SET_MODAL_INFO = "SET_MODAL_INFO";
export const SET_MODAL_NEW_SHOW = "SET_MODAL_NEW_SHOW";
export const SET_MODAL_EDIT_SHOW = "SET_MODAL_EDIT_SHOW";
export const SET_MODAL_DELETE_SHOW = "SET_MODAL_DELETE_SHOW";

export const SET_TOAST_INFO = "SET_TOAST_INFO";
export const SET_TOAST_SHOW = "SET_TOAST_SHOW";
